### ISSUE TITLE
Flatpak gnome 3.38 platform end of life

### ISSUE THREAD

**Issue by hparlak** [neatdecisions/detwinner#22]
I got this message when updating flatpak, which I guess needs to be addressed

Info: org.gnome.Platform//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.neatdecisions.Detwinner

**Comment by BurnerWah** [comment]
This has been fixed. flathub/com.neatdecisions.Detwinner#12
