### ISSUE TITLE
Thanks and a suggestion

### ISSUE THREAD

**Issue by pizzadude** [neatdecisions/detwinner#3]
Hi, I found this on flathub and I'd like to thank you for making this as it works pretty good. I use Fedora KDE. One note though is the description "duplicate file finder for GNOME environment", wouldn't it be better to say "duplicate finder for the Linux desktop" as you don't have to use Gnome to use this application. Anyways thanks!

**Comment by neatdecisions** [comment]
Thanks for the suggestion - it's done now!
